name: Run Tests with Docker + Allure

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v3

      - name: 🐳 Build da imagem Docker
        run: docker build -t dog-api-tests .

      - name: ▶️ Rodar testes no container
        run: docker run --rm -v ${{ github.workspace }}:/app dog-api-tests

      - name: 📦 Upload do relatório Allure
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report