name: CI - Testes API

on:
  push:
    branches: [ "main" ]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Rodar testes
        run: mvn clean test